version: '3'
services:
  rclone-index:
    build: ./rclone-index
    ports:
      - "8080:8080"
    environment:
      - CONFIG_BASE64=${CONFIG_BASE64}
      - CONFIG_URL=${CONFIG_URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DARK_MODE=${DARK_MODE}
  discord-bot:
    build: ./discord-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
