version: '3.8'
services:
  combined-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_BASE64=${CONFIG_BASE64}
      - CONFIG_URL=${CONFIG_URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DARK_MODE=${DARK_MODE}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
